@order-service = reddog.whitebush-a2e52ffc.eastus2.azurecontainerapps.io
@storeId = Redmond

### Create an order via order-service POST
POST https://{{order-service}}/order
Content-Type: application/json
 
{
    "storeId": "{{storeId}}",
    "customerName": "John 'Hannibal' Smith",
    "loyaltyId": "42",
    "orderItems": [
        {
            "menuItemId": 1,
            "quantity": 1
        },
        {
            "menuItemId": 2,
            "quantity": 1
        },
        {
            "menuItemId": 3,
            "quantity": 3
        }
    ]
}
