### Create an order via order-service POST
POST https://reddog.icydesert-8a2d7e99.eastus2.azurecontainerapps.io/order
Content-Type: application/json
 
{
    "storeId": "Redmond",
    "customerName": "John Smith",
    "loyaltyId": "42",
    "orderItems": [
        {
            "menuItemId": 1,
            "quantity": 1
        },
        {
            "menuItemId": 2,
            "quantity": 1
        },
        {
            "menuItemId": 3,
            "quantity": 3
        }
    ]
}
